# Generated by Django 6.0.3 on 2026-04-12 08:45

import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinioStorageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=services.models.MinioStorage(), upload_to=services.models.get_s3_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='PGVectorDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
