# create a small seperate project for handling docker and docker compose


services:
  django-backend:
    build: 
      context: ./src
      args: 
        HF_TOKEN: ${HF_TOKEN}
    working_dir: /app/main
    volumes:
      - ./src/:/app/
    command: uv run python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app

  rabbitmq:
    restart: always
    image: rabbitmq:latest
    ports:
      - "15672:15672"
    expose:
      - "5672"
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

# create one service for celery, celery beat and flower
# remove the volume definition from celery
  celery:
    build: 
      context: ./src
      args: 
        HF_TOKEN: ${HF_TOKEN}
    working_dir: /app/main
    command: uv run celery -A backend worker -l info
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - ./src/:/app
    depends_on:
      - db
      - rabbitmq

  celery-beat:
    build: 
      context: ./src
      args: 
        HF_TOKEN: ${HF_TOKEN}
    working_dir: /app/main
    command: uv run celery -A backend beat -l info
    environment:
      - OLLAMA_BASE_URL=http://localhost:11434
    volumes:
      - ./src/:/app
    depends_on:
      - rabbitmq

  flower:
    build: 
      context: ./src
      args: 
        HF_TOKEN: ${HF_TOKEN}
    working_dir: /app/main
    command: uv run celery -A backend flower --port=5555
    environment:
      - OLLAMA_BASE_URL=http://localhost:11434
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq

  db:
    image: ankane/pgvector
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
    - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  minio:
    image: minio/minio
    hostname: "minio"
    volumes:
      - minio_files:/data
    env_file:
      - .env
    command: 'minio server /data --console-address ":9001"'
    ports:
      - 9000:9000
      - 9001:9001

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb --quiet myminio/docs;
      /usr/bin/mc policy set download myminio/docs;
      "


volumes:
  postgres_data:
  minio_files:
