version: '3.8'
services:
  taskmaster-api:
    build: .
    container_name: taskmaster_fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./sources:/app/sources:ro
    env_file:
      - .env
    
    networks:
      - taskmaster-network
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app/src

networks:
  taskmaster-network:
    external: true