version: '3.8'
services:
  django-backend:
    build: ./src
    working_dir: /app/main
    volumes:
      - ./src/:/app/
    command: uv run python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app

  rabbitmq:
    restart: always
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  celery:
    build: ./src
    working_dir: /app/main
    command: uv run celery -A backend worker -l info
    volumes:
      - ./src/:/app
    depends_on:
      - db
      - rabbitmq

  celery-beat:
    build: ./src
    working_dir: /app/main
    command: uv run celery -A backend beat -l info
    volumes:
      - ./src/:/app
    depends_on:
      - rabbitmq

  db:
    image: ankane/pgvector
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
    - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  minio:
    image: minio/minio
    hostname: "minio"
    volumes:
      - ./minio:/minio_files
    env_file:
      - .env
    command: 'minio server /minio_files --console-address ":9001"'
    ports:
      - 9000:9000
      - 9001:9001

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb --quiet myminio/docs;
      /usr/bin/mc policy set none myminio/docs;
      "


volumes:
  postgres_data:
  minio_data: