# Generated by Django 6.0.3 on 2026-03-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('page_number', models.IntegerField()),
                ('source_id', models.IntegerField(help_text='The ID from the Gutenberg API', unique=True)),
            ],
        ),
    ]
