# Generated by Django 6.0.3 on 2026-03-23 21:01

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BARTModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='docs')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('embedding_clip_vit_l_14', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('parent_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='bart.bartmodel')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding_clip_vit_l_14'], m=16, name='clip_l14_idx', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
