# Generated by Django 6.0.3 on 2026-03-20 17:42

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='page_number',
            new_name='page_num',
        ),
        migrations.AddField(
            model_name='book',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='source_id',
            field=models.IntegerField(unique=True),
        ),
    ]
