# Generated by Django 6.0.3 on 2026-03-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='llm_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
