# Generated by Django 6.0.3 on 2026-04-15 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bart', '0001_initial'),
        ('documents', '0002_alter_document_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bartquery',
            name='response',
        ),
        migrations.AddField(
            model_name='bartquery',
            name='llm_response',
            field=models.TextField(blank=True, default='', verbose_name='Response'),
        ),
        migrations.AlterField(
            model_name='bartquery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='bartquery',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='documents.document', verbose_name='Query Model'),
        ),
        migrations.AlterField(
            model_name='bartquery',
            name='prompt',
            field=models.TextField(max_length=2000, verbose_name='Prompt'),
        ),
    ]
