# Generated by Django 6.0.3 on 2026-03-28 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bart', '0002_documentchunk_llm_summary'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BARTQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(max_length=2000)),
                ('response', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='documentchunk',
            name='clip_l14_idx',
        ),
        migrations.AddField(
            model_name='bartquery',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='documents.document'),
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='parent_doc',
        ),
        migrations.DeleteModel(
            name='BARTModel',
        ),
        migrations.DeleteModel(
            name='DocumentChunk',
        ),
    ]
