# Generated by Django 6.0.3 on 2026-03-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bart', '0002_rename_page_number_book_page_num_book_embedding_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='page_num',
            new_name='page_number',
        ),
    ]
