# Generated by Django 6.0.3 on 2026-03-20 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bart', '0003_rename_page_num_book_page_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='source_id',
        ),
    ]
