# Generated by Django 6.0.3 on 2026-04-06 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentchunk',
            name='content',
        ),
        migrations.AddField(
            model_name='documentpages',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
        migrations.AddField(
            model_name='documenttext',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
        migrations.AddField(
            model_name='documenttext',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='documenttextchunk',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_chunks', to='documents.documenttext'),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document'),
        ),
    ]
