# Generated by Django 6.0.3 on 2026-04-15 14:39

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='document',
            name='minio_bucket',
            field=models.CharField(default='docs', max_length=63, verbose_name="User's MinIO Bucket Name"),
        ),
        migrations.AlterField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Document Owner'),
        ),
        migrations.AlterField(
            model_name='document',
            name='process_state',
            field=models.CharField(choices=[('get_document', 'Get Document'), ('upload_document', 'Upload Document'), ('extract_pdf_text', 'Extract PDF Text'), ('split_text_into_chunks', 'Split Text Into Chunks'), ('embed_chunks', 'Embed Chunks'), ('save_to_pgvector', 'Save to PGVector'), ('save_to_minio', 'Save to MinIO')], default='get_document', max_length=32, verbose_name='Document Processing State'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='documentchunkembedding',
            name='chunk_index',
            field=models.PositiveIntegerField(verbose_name='Chunk Index'),
        ),
        migrations.AlterField(
            model_name='documentchunkembedding',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document', verbose_name='Document Chunk Embedding'),
        ),
        migrations.AlterField(
            model_name='documentchunkembedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True, verbose_name='Chunk Embedding'),
        ),
        migrations.AlterField(
            model_name='documentpages',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.document', verbose_name='Document Pages'),
        ),
        migrations.AlterField(
            model_name='documentpages',
            name='pages',
            field=models.PositiveIntegerField(verbose_name='Number of Pages'),
        ),
        migrations.AlterField(
            model_name='documenttext',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.document', verbose_name='Document Text'),
        ),
        migrations.AlterField(
            model_name='documenttext',
            name='text',
            field=models.TextField(verbose_name='Document Text'),
        ),
        migrations.AlterField(
            model_name='documenttextchunk',
            name='chunk_index',
            field=models.PositiveIntegerField(verbose_name='Chunk Index'),
        ),
        migrations.AlterField(
            model_name='documenttextchunk',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Chunk Content'),
        ),
        migrations.AlterField(
            model_name='documenttextchunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_chunks', to='documents.documenttext', verbose_name='Document Text Chunk'),
        ),
    ]
