# Generated by Django 6.0.3 on 2026-03-29 11:31

import private_storage.fields
import private_storage.storage.s3boto3
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_owner_minio_bucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.s3boto3.PrivateS3BotoStorage(), upload_to='docs/', verbose_name='File'),
        ),
    ]
