# Generated by Django 6.0.3 on 2026-04-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_file_alter_document_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='docs', verbose_name='File'),
        ),
    ]
